<a href="https://colab.research.google.com/github/facundolubo/CoderHouse/blob/main/Clase_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bases de numpy

## Creacion de ndarrays

In [ ]:
import numpy as np
Npa = np.array(range(10))
Npa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
Np_cero = np.zeros(10)
Np_cero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
Np_cero_int = np.zeros(10, dtype=int)
Np_cero_int

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
Np_uno = np.ones(10)
Np_uno

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
Np_relleno = np.full(10,256)
Np_relleno

array([256, 256, 256, 256, 256, 256, 256, 256, 256, 256])

In [ ]:
Np_rango = np.arange(10)
Np_rango

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
Np_random_dimensiones = np.random.randint(10, size=(3, 4))
Np_random_dimensiones

array([[4, 6, 4, 5],
       [7, 3, 0, 2],
       [6, 2, 1, 6]])

## Tipos de datos en arrays

In [ ]:
# Verificando el tipo de dato de array
arr = np.array([1, 2, 3, 4])
print(arr.dtype) 

int64


In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype) 

<U6


In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype) 

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr);print(arr.dtype) 

[1 2 3 4]
int32


In [ ]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype) 

[1 2 3]
int32


In [ ]:
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype) 

[ True False  True]
bool


## Atributos de los ndarrays

In [ ]:
Np_cero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
Np_cero.ndim

1

In [ ]:
Np_random_dimensiones

array([[4, 6, 4, 5],
       [7, 3, 0, 2],
       [6, 2, 1, 6]])

In [ ]:
Np_random_dimensiones.ndim

2

In [ ]:
Np_random_dimensiones.shape

(3, 4)

In [ ]:
Np_random_dimensiones.size

12

In [ ]:
Np_cero.dtype

dtype('float64')

In [ ]:
Np_cero_int.dtype

dtype('int64')

In [ ]:
Np_random_dimensiones.itemsize

8

In [ ]:
Np_cero.nbytes

80

In [ ]:
Np_cero_int.nbytes

80

# Indexamiento y acceso

In [ ]:
rango = range(1,11)
Np_diez_numeros = np.array(rango)
Np_diez_numeros

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
Np_diez_numeros[0]

1

In [ ]:
Np_diez_numeros[[0,4]]

array([1, 5])

In [ ]:
Np_diez_numeros[4]

5

In [ ]:
Np_diez_numeros[-1]

10

In [ ]:
Np_diez_numeros[-2]

9

In [ ]:
Np_random_dimensiones

array([[4, 6, 4, 5],
       [7, 3, 0, 2],
       [6, 2, 1, 6]])

In [ ]:
Np_random_dimensiones[-2, -1]

2

In [ ]:
Np_random_dimensiones[1, 3]

2

## Accediendo a subarrays

In [ ]:
Np_diez_numeros

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
Np_diez_numeros[::]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
Np_diez_numeros[1:4]

array([2, 3, 4])

In [ ]:
Np_diez_numeros[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [ ]:
Np_diez_numeros[4:7]

array([5, 6, 7])

In [ ]:
Np_diez_numeros[0:5:2]

array([1, 3, 5])

In [ ]:
Np_diez_numeros[::-2]

array([10,  8,  6,  4,  2])

In [ ]:
Np_random_dimensiones[2,]

array([1, 6, 6, 8])

In [ ]:
Np_random_dimensiones

array([[4, 6, 4, 5],
       [7, 3, 0, 2],
       [6, 2, 1, 6]])

In [ ]:
Np_random_dimensiones[:2, 1:3]

array([[6, 4],
       [3, 0]])

In [ ]:
Np_random_dimensiones[:2, :2]

array([[7, 9],
       [0, 9]])

In [ ]:
Np_random_dimensiones[2, 3]

8

# Reshape

In [ ]:
np.arange(1,65)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [ ]:
np.arange(1,65)
Ajedrez_64 = np.arange(1,65).reshape(8,8)
Ajedrez_64

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

# Concatenate

In [ ]:
Array_1 = np.random.randint(10, size=5)
Array_1
Array_2 = np.random.randint(10, size=5)
Array_2

array([3, 9, 5, 2, 6])

In [ ]:
np.concatenate?

In [ ]:
Array_1 = np.random.randint(10, size=5)
Array_2 = np.random.randint(10, size=5)
Arrays_concatenados = np.concatenate([Array_1, Array_2])
Arrays_concatenados

array([8, 7, 2, 6, 3, 5, 1, 4, 1, 5])

In [ ]:
Array_extra = np.array([[10],[20]])
Array_extra

array([[10],
       [20]])

# Apilamiento

In [ ]:
Array_apilados_v = np.vstack([Array_extra, Array_extra])
Array_apilados_v

array([[10],
       [20],
       [10],
       [20]])

In [ ]:
Array_apilados_h = np.hstack([Array_extra, Array_extra])
Array_apilados_h

array([[10, 10],
       [20, 20]])

In [ ]:
Arrays_concatenados

array([1, 9, 4, 7, 8, 8, 2, 1, 5, 1])

# Splitting

In [ ]:
Array_partido = np.split(Arrays_concatenados, [2])
Array_partido

[array([8, 7]), array([2, 6, 3, 5, 1, 4, 1, 5])]

In [ ]:
Array_partido_2 = np.split(Arrays_concatenados, [2, 8])
Array_partido_2

[array([8, 7]), array([2, 6, 3, 5, 1, 4]), array([1, 5])]

In [ ]:
Parte_1, Parte_2, Parte_3 = Array_partido_2
Parte_1

array([8, 7])

In [ ]:
Parte_2

array([2, 6, 3, 5, 1, 4])

In [ ]:
Parte_3

array([1, 5])

In [ ]:
Ajedrez_partido_1 = np.hsplit(Ajedrez_64, [4])
Ajedrez_partido_1

[array([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12],
        [17, 18, 19, 20],
        [25, 26, 27, 28],
        [33, 34, 35, 36],
        [41, 42, 43, 44],
        [49, 50, 51, 52],
        [57, 58, 59, 60]]), array([[ 5,  6,  7,  8],
        [13, 14, 15, 16],
        [21, 22, 23, 24],
        [29, 30, 31, 32],
        [37, 38, 39, 40],
        [45, 46, 47, 48],
        [53, 54, 55, 56],
        [61, 62, 63, 64]])]

In [ ]:
Ajedrez_partido_2 = np.vsplit(Ajedrez_64, [4])
Ajedrez_partido_2

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32]]),
 array([[33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55, 56],
        [57, 58, 59, 60, 61, 62, 63, 64]])]

# Agregaciones

## Manera antigua 😶

In [ ]:
Array_aleatorio = np.random.randint(10, size=10)
Array_aleatorio

array([9, 0, 7, 9, 8, 5, 0, 1, 2, 4])

In [ ]:
Array_aleatorio = np.random.randint(10, size=10)
print(Array_aleatorio)
suma = 0
for i in Array_aleatorio:
    suma += i
promedio = suma / np.size(Array_aleatorio)
promedio

[9 1 2 5 0 6 3 6 6 4]


4.2

## Manera divertida 🤗

In [ ]:
Array_aleatorio.sum()

42

In [ ]:
Array_aleatorio.mean()

4.2

In [ ]:
Array_aleatorio.max()

9

In [ ]:
np.median(Array_aleatorio)

4.5

In [ ]:
np.std(Array_aleatorio)

2.6

In [ ]:
np.var(Array_aleatorio)

6.760000000000001

# Operaciones vectorizadas

In [ ]:
Array_1

array([1, 9, 4, 7, 8])

In [ ]:
Array_2

array([8, 2, 1, 5, 1])

In [ ]:
Array_1+5

array([ 6, 14,  9, 12, 13])

In [ ]:
Array_1 + Array_2

array([ 9, 11,  5, 12,  9])

In [ ]:
np.add(Array_1, Array_2)

array([ 9, 11,  5, 12,  9])

In [ ]:
np.matmul(Array_1, Array_2)

73